# Generated by Django 4.2.30 on 2026-07-20 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SleepLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("date", models.DateField()),
                ("bedtime", models.DateTimeField()),
                ("sleep_at", models.DateTimeField()),
                ("wake_at", models.DateTimeField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=4)),
                ("awakenings", models.PositiveSmallIntegerField(default=0)),
                ("quality", models.PositiveSmallIntegerField()),
                ("morning_energy", models.PositiveSmallIntegerField()),
                (
                    "pre_sleep_activity",
                    models.CharField(
                        choices=[
                            ("screen", "screen"),
                            ("reading", "reading"),
                            ("exercise", "exercise"),
                            ("meal", "meal"),
                            ("caffeine", "caffeine"),
                            ("alcohol", "alcohol"),
                            ("meditation", "meditation"),
                            ("work", "work"),
                            ("none", "none"),
                            ("other", "other"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["user", "date"], name="sleep_sleep_user_id_dba909_idx")
                ],
            },
        ),
    ]
