# Generated by Django 4.2.30 on 2026-07-20 09:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("doctor", models.CharField(blank=True, max_length=40, null=True)),
                ("department", models.CharField(blank=True, max_length=40, null=True)),
                ("location", models.CharField(max_length=80)),
                ("reason", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "scheduled"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                            ("no_show", "no_show"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "reminder_minutes_before",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10080),
                        ],
                    ),
                ),
                ("follow_up_needed", models.BooleanField()),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("daily_summary", "daily_summary")],
                        default="daily_summary",
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("date", models.DateField()),
                (
                    "steps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200000),
                        ],
                    ),
                ),
                (
                    "walk_time_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "stand_time_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "active_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "sedentary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "manual"),
                            ("apple_health", "apple_health"),
                            ("wearable", "wearable"),
                            ("import", "import"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField()),
                ("notes", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("檢驗報告", "檢驗報告"),
                            ("影像報告", "影像報告"),
                            ("診斷證明", "診斷證明"),
                            ("收據/費用", "收據/費用"),
                            ("轉診單", "轉診單"),
                            ("病歷摘要", "病歷摘要"),
                            ("其他", "其他"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("provider", models.CharField(blank=True, max_length=60, null=True)),
                ("file_name", models.CharField(blank=True, max_length=120, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=60, null=True)),
                ("file_data_url", models.TextField(blank=True, null=True)),
                (
                    "file_size_kb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_documents",
                        to="health_records.appointment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["user", "date"], name="health_reco_user_id_6ba4d5_idx"),
                    models.Index(
                        fields=["user", "category"], name="health_reco_user_id_f4bdc8_idx"
                    ),
                    models.Index(
                        fields=["user", "appointment"], name="health_reco_user_id_2fc565_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["user", "start_at"], name="health_reco_user_id_2afa55_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["user", "status"], name="health_reco_user_id_61f606_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["user", "date"], name="health_reco_user_id_6afd85_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["user", "source"], name="health_reco_user_id_057770_idx"),
        ),
    ]
