# Generated by Django 4.2.30 on 2026-07-20 09:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=60)),
                ("icon", models.CharField(max_length=4)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("boolean", "boolean"),
                            ("count", "count"),
                            ("numeric", "numeric"),
                            ("duration", "duration"),
                        ],
                        max_length=16,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "increment",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("schedule", models.JSONField()),
                ("reminder_time", models.CharField(blank=True, max_length=5, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=280, null=True)),
                ("sort_order", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("date", models.DateField()),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                ("logged_at", models.DateTimeField()),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "habit", "date"], name="habits_habi_user_id_345b41_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(fields=["user", "archived"], name="habits_habi_user_id_b9d852_idx"),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "sort_order"], name="habits_habi_user_id_92ff2f_idx"
            ),
        ),
    ]
