# Generated by Django 4.2.30 on 2026-07-20 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="", max_length=2000)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("all_day", models.BooleanField()),
                ("tz", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("meeting", "meeting"),
                            ("task", "task"),
                            ("personal", "personal"),
                            ("health", "health"),
                            ("reminder", "reminder"),
                            ("other", "other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recurrence_rule",
                    models.CharField(blank=True, default=None, max_length=500, null=True),
                ),
                ("task_id", models.UUIDField(blank=True, default=None, null=True)),
                ("location", models.CharField(blank=True, default=None, max_length=200, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "start_at"], name="calendar_ca_user_id_9c10da_idx"
                    ),
                    models.Index(fields=["user", "end_at"], name="calendar_ca_user_id_d76bb3_idx"),
                    models.Index(fields=["user", "task_id"], name="calendar_ca_user_id_0a160c_idx"),
                ],
            },
        ),
    ]
