# Generated by Django 4.2.30 on 2026-07-20 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True, default="", max_length=200000)),
                ("folder", models.CharField(blank=True, default="", max_length=200)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("pinned", models.BooleanField(default=False)),
                ("is_daily", models.BooleanField(default=False)),
                ("daily_date", models.DateField(blank=True, null=True)),
                ("project_id", models.CharField(blank=True, default="", max_length=64)),
                ("project_name", models.CharField(blank=True, default="", max_length=200)),
                ("task_id", models.CharField(blank=True, default="", max_length=64)),
                ("task_title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NoteVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("content", models.TextField(blank=True, default="", max_length=200000)),
                ("folder", models.CharField(blank=True, default="", max_length=200)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual_save", "manual_save"),
                            ("auto_snapshot", "auto_snapshot"),
                            ("restore", "restore"),
                            ("conflict_branch", "conflict_branch"),
                        ],
                        default="manual_save",
                        max_length=20,
                    ),
                ),
                ("note_version_at_snapshot", models.PositiveIntegerField()),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="notes.note",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["user", "note"], name="notes_notev_user_id_c584de_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["user", "folder"], name="notes_note_user_id_a0fb88_idx"),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["user", "pinned"], name="notes_note_user_id_3284b2_idx"),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["user", "is_daily", "daily_date"], name="notes_note_user_id_62b2c0_idx"
            ),
        ),
    ]
