# Generated by Django 4.2.30 on 2026-07-20 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "planning"),
                            ("active", "active"),
                            ("on_hold", "on_hold"),
                            ("completed", "completed"),
                            ("archived", "archived"),
                        ],
                        db_index=True,
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(default="#8a6a52", max_length=20)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("milestones", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inbox", "inbox"),
                            ("planned", "planned"),
                            ("in_progress", "in_progress"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                        ],
                        db_index=True,
                        default="inbox",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("med", "med"),
                            ("high", "high"),
                            ("urgent", "urgent"),
                        ],
                        db_index=True,
                        default="med",
                        max_length=10,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("estimate_min", models.PositiveIntegerField(blank=True, null=True)),
                ("actual_min", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "energy",
                    models.CharField(
                        blank=True,
                        choices=[("low", "low"), ("med", "med"), ("high", "high")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("context", models.CharField(blank=True, max_length=200, null=True)),
                ("recurrence_rule", models.CharField(blank=True, max_length=200, null=True)),
                ("depends_on", models.JSONField(blank=True, default=list)),
                ("remind_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("archived", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="tasks.task",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="tasks.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["user", "status"], name="tasks_task_user_id_c0fce1_idx"),
                    models.Index(fields=["user", "project"], name="tasks_task_user_id_725a32_idx"),
                    models.Index(fields=["user", "parent"], name="tasks_task_user_id_04012e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=40)),
                ("color", models.CharField(default="#6b6b6b", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["user", "name"], name="tasks_tag_user_id_926090_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["user", "status"], name="tasks_proje_user_id_fce9e0_idx"),
        ),
    ]
