# Generated by Django 4.2.30 on 2026-07-20 09:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimerSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("label", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pomodoro", "pomodoro"),
                            ("deep_work", "deep_work"),
                            ("meeting", "meeting"),
                            ("study", "study"),
                            ("admin", "admin"),
                            ("exercise", "exercise"),
                            ("break", "break"),
                            ("other", "other"),
                        ],
                        default="deep_work",
                        max_length=20,
                    ),
                ),
                ("task_id", models.UUIDField(blank=True, null=True)),
                ("project_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("paused", "paused"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("stopwatch", "stopwatch"), ("pomodoro", "pomodoro")],
                        default="stopwatch",
                        max_length=20,
                    ),
                ),
                (
                    "target_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("session_start_at", models.DateTimeField()),
                ("accumulated_seconds", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pomodoro_phase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("focus", "focus"),
                            ("short_break", "short_break"),
                            ("long_break", "long_break"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("pomodoro_count", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("label", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pomodoro", "pomodoro"),
                            ("deep_work", "deep_work"),
                            ("meeting", "meeting"),
                            ("study", "study"),
                            ("admin", "admin"),
                            ("exercise", "exercise"),
                            ("break", "break"),
                            ("other", "other"),
                        ],
                        default="deep_work",
                        max_length=20,
                    ),
                ),
                ("task_id", models.UUIDField(blank=True, null=True)),
                ("project_id", models.UUIDField(blank=True, null=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("duration_seconds", models.PositiveIntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[("timer", "timer"), ("manual", "manual")], max_length=10
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "timer_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_entries",
                        to="focus.timersession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="timersession",
            index=models.Index(fields=["user", "status"], name="focus_timer_user_id_ffb238_idx"),
        ),
        migrations.AddIndex(
            model_name="timersession",
            index=models.Index(fields=["user", "deleted"], name="focus_timer_user_id_669154_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["user", "start_at"], name="focus_timee_user_id_6c6bf6_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["user", "deleted"], name="focus_timee_user_id_6f8e02_idx"),
        ),
    ]
