# Generated by Django 4.2.30 on 2026-07-20 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SymptomDef",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=30)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("疼痛", "疼痛"),
                            ("痠", "痠"),
                            ("麻", "麻"),
                            ("腫脹", "腫脹"),
                            ("疲勞", "疲勞"),
                            ("頭痛", "頭痛"),
                            ("情緒", "情緒"),
                            ("壓力", "壓力"),
                            ("自訂", "自訂"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                ("archived", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SymptomLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("date", models.DateField(db_index=True)),
                ("start_at", models.DateTimeField()),
                ("intensity", models.DecimalField(decimal_places=1, max_digits=4)),
                ("body_location", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "duration_min",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
                ),
                ("triggers", models.JSONField(blank=True, default=list)),
                ("relief", models.JSONField(blank=True, default=list)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                ("photo", models.TextField(blank=True, null=True)),
                (
                    "symptom_def",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="symptoms.symptomdef",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "symptom_def"], name="symptoms_sy_user_id_38d2ee_idx"
                    ),
                    models.Index(fields=["user", "date"], name="symptoms_sy_user_id_6b9326_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="symptomdef",
            index=models.Index(fields=["user", "archived"], name="symptoms_sy_user_id_83636a_idx"),
        ),
    ]
