# Generated by Django 4.2.30 on 2026-07-20 09:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationSchedule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("medication_id", models.UUIDField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[("medication", "medication"), ("supplement", "supplement")],
                        max_length=16,
                    ),
                ),
                ("time_of_day", models.CharField(max_length=5)),
                ("label", models.CharField(blank=True, max_length=40, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicationLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("medication_id", models.UUIDField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[("medication", "medication"), ("supplement", "supplement")],
                        max_length=16,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("taken", "taken"), ("missed", "missed"), ("skipped", "skipped")],
                        max_length=16,
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="meds.medicationschedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=80)),
                (
                    "dose",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("unit", models.CharField(max_length=20)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "daily"),
                            ("specific-days", "specific-days"),
                            ("every-n-days", "every-n-days"),
                            ("as-needed", "as-needed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                (
                    "interval_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                ("times", models.JSONField(blank=True, default=list)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "with_food",
                    models.CharField(
                        choices=[
                            ("with_food", "with_food"),
                            ("empty_stomach", "empty_stomach"),
                            ("either", "either"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "remaining_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("refill_reminder", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=280, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Supplement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=80)),
                (
                    "dose",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("unit", models.CharField(max_length=20)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "daily"),
                            ("specific-days", "specific-days"),
                            ("every-n-days", "every-n-days"),
                            ("as-needed", "as-needed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                (
                    "interval_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                ("times", models.JSONField(blank=True, default=list)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "with_food",
                    models.CharField(
                        choices=[
                            ("with_food", "with_food"),
                            ("empty_stomach", "empty_stomach"),
                            ("either", "either"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "remaining_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("refill_reminder", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=280, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["user", "active"], name="meds_supple_user_id_e01f77_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="medicationschedule",
            index=models.Index(
                fields=["user", "medication_id", "source_type"],
                name="meds_medica_user_id_b81261_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicationlog",
            index=models.Index(
                fields=["user", "medication_id", "source_type"],
                name="meds_medica_user_id_8ea022_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicationlog",
            index=models.Index(
                fields=["user", "scheduled_for"], name="meds_medica_user_id_d7275e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medication",
            index=models.Index(fields=["user", "active"], name="meds_medica_user_id_11bfcd_idx"),
        ),
    ]
