# Generated by Django 4.2.30 on 2026-07-20 09:33

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RehabPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=60)),
                ("body_region", models.CharField(blank=True, max_length=30, null=True)),
                ("diagnosis", models.CharField(blank=True, max_length=120, null=True)),
                ("goal", models.CharField(blank=True, max_length=200, null=True)),
                ("therapist_name", models.CharField(blank=True, max_length=30, null=True)),
                ("clinic_name", models.CharField(blank=True, max_length=40, null=True)),
                ("active", models.BooleanField()),
                ("start_date", models.DateField()),
                ("next_appointment_at", models.DateField(blank=True, null=True)),
                ("general_cautions", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "review_notes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RehabExercise",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=60)),
                ("instructions", models.CharField(blank=True, max_length=600, null=True)),
                ("media", models.CharField(blank=True, max_length=300, null=True)),
                ("sets", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("reps", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("duration_sec", models.PositiveIntegerField(blank=True, null=True)),
                ("load_limit", models.CharField(blank=True, max_length=40, null=True)),
                ("angle", models.CharField(blank=True, max_length=40, null=True)),
                ("cautions", models.CharField(blank=True, max_length=300, null=True)),
                ("frequency", models.CharField(blank=True, max_length=60, null=True)),
                ("therapist_note", models.CharField(blank=True, max_length=300, null=True)),
                ("effective_date", models.DateField()),
                ("stop_date", models.DateField(blank=True, null=True)),
                ("order", models.IntegerField(blank=True, null=True)),
                (
                    "rehab_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="rehab.rehabplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RehabSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted", models.BooleanField(default=False)),
                ("date", models.DateField()),
                ("done", models.BooleanField()),
                ("actual_sets", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("actual_reps", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("actual_time", models.PositiveIntegerField(blank=True, null=True)),
                ("discomfort_before", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("discomfort_after", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("load", models.CharField(blank=True, max_length=40, null=True)),
                ("notes", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "rehab_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="rehab.rehabexercise",
                    ),
                ),
                (
                    "rehab_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="rehab.rehabplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "rehab_plan"], name="rehab_rehab_user_id_2c2609_idx"
                    ),
                    models.Index(
                        fields=["user", "rehab_exercise"], name="rehab_rehab_user_id_1511c1_idx"
                    ),
                    models.Index(fields=["user", "date"], name="rehab_rehab_user_id_afc5c7_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="rehabplan",
            index=models.Index(fields=["user", "active"], name="rehab_rehab_user_id_a7fd2f_idx"),
        ),
        migrations.AddIndex(
            model_name="rehabexercise",
            index=models.Index(
                fields=["user", "rehab_plan"], name="rehab_rehab_user_id_c4c30b_idx"
            ),
        ),
    ]
